sudo: required

language: cpp
compiler:
    - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - smspillaz/cmake-2.8.12
        packages:
            - gcc-5
            - g++-5
            - libgtest-dev
            - cmake

        coverity_scan:
            name: MatrixLibs
            version: 1.0
            description: matrix library
            notification_email: michalkielan6@gmail.com


before_script:
    - git clone https://github.com/google/benchmark
    - cd benchmark
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
    - cd ../..
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script: 
    - mkdir build
    - cd build
    - cmake .. 
    - make 
    - make test

branch_pattern: master
