sudo: required

language: cpp
compiler:
    - gcc
    - clang

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - g++-6
            - lcov
            - libgtest-dev
            - cmake
            - cmake-data

        coverity_scan:
            name: MatrixLibs
            version: 1.0
            description: matrix library
            notification_email: michalkielan6@gmail.com


before_script:
#    - git clone https://github.com/google/benchmark
#    - cd benchmark
#    - mkdir build
#    - cd build
#    - cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_LTO=true ..
#   - make
#    - sudo make install
#    - cd ../..
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script: 
    - mkdir build
    - cd build
    - cmake -DBUILD_BENCH=OFF .. 
    - make 
    - make test

branch_pattern: master
